// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using invoice_api.Data;

#nullable disable

namespace invoice_api.Migrations
{
    [DbContext(typeof(IdeoDbContext))]
    partial class IdeoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

            modelBuilder.Entity("invoice_api.Data.Entities.BillingStatusEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BillingStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            StatusName = "Pending"
                        },
                        new
                        {
                            Id = 2,
                            StatusName = "Paid"
                        },
                        new
                        {
                            Id = 3,
                            StatusName = "Overdue"
                        });
                });

            modelBuilder.Entity("invoice_api.Data.Entities.CustomerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("SubscripsionPeriod")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Surname")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "New York, USA",
                            Email = "jdow@gmail.com",
                            Name = "John",
                            SubscripsionPeriod = 2,
                            Surname = "Dow"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Tel Aviv, Israel",
                            Email = "iisraeli@gmail.com",
                            Name = "Israel",
                            SubscripsionPeriod = 3,
                            Surname = "Israeli"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Saint Petersburg, Russian Federation",
                            Email = "vpupkin@mail.ru",
                            Name = "Vasiliy",
                            SubscripsionPeriod = 1,
                            Surname = "Pupkin"
                        });
                });

            modelBuilder.Entity("invoice_api.Data.Entities.InvoiceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<int>("BillingStatusId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Invoices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 100m,
                            BillingStatusId = 2,
                            CreateDate = new DateTime(2023, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 1,
                            Description = "Tools"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 1000m,
                            BillingStatusId = 2,
                            CreateDate = new DateTime(2023, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 2,
                            Description = "Software"
                        },
                        new
                        {
                            Id = 3,
                            Amount = 300m,
                            BillingStatusId = 2,
                            CreateDate = new DateTime(2023, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 3,
                            Description = "Toys"
                        },
                        new
                        {
                            Id = 4,
                            Amount = 800m,
                            BillingStatusId = 1,
                            CreateDate = new DateTime(2023, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 2,
                            Description = "Vinille music disks"
                        },
                        new
                        {
                            Id = 5,
                            Amount = 150m,
                            BillingStatusId = 3,
                            CreateDate = new DateTime(2023, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 3,
                            Description = "Vitamins"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
